# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
# title: HT-Step article grounding challenge (full temporal segments)
title: HT-Step article grounding challenge (temporal segment detection)
short_description: Step grounding evaluation on the HT-Step benchmark
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Leaderboard for single-timestamp temporal grounding evaluation on HT-Step.
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2019-01-01 00:00:00
end_date: 2099-05-31 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["mAP"],
        "default_order_by": "mAP",
        "metadata": {
          "mAP": {
            "sort_ascending": True,
            "description": "Article grounding mAP output for leaderboard.",
          },
        }
      }
  - id: 2
    schema:
      {
        "labels": ["mAP"],
        "default_order_by": "mAP",
        "metadata": {
          "mAP": {
            "sort_ascending": True,
            "description": "Article grounding mAP output for leaderboard.",
          },
        }
      }
  - id: 3
    schema:
      {
        "labels": ["mAP"],
        "default_order_by": "mAP",
        "metadata": {
          "mAP": {
            "sort_ascending": True,
            "description": "Article grounding mAP output for leaderboard.",
          },
        }
      }
      

challenge_phases:
  - id: 1
    name: Seen Test Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2019-01-01 00:00:00
    end_date: 2099-05-24 23:59:59
    test_annotation_file: annotations/annotations_seen_test.json
    codename: test_seen
    max_submissions_per_day: 10
    max_submissions_per_month: 50
    max_submissions: 100
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    # submission_meta_attributes:
      # - name: TextAttribute
      #   description: Sample
      #   type: text
      # - name: SingleOptionAttribute
      #   description: Sample
      #   type: radio
      #   options: ["A", "B", "C"]
      # - name: MultipleChoiceAttribute
      #   description: Sample
      #   type: checkbox
      #   options: ["alpha", "beta", "gamma"]
      # - name: TrueFalseField
      #   description: Sample
      #   type: boolean
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

  - id: 2
    name: Unseen Test Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: False
    is_public: False
    is_submission_public: False
    start_date: 2019-01-01 00:00:00
    end_date: 2099-05-24 23:59:59
    test_annotation_file: annotations/annotations_unseen_test.json
    codename: test_unseen
    max_submissions_per_day: 10
    max_submissions_per_month: 50
    max_submissions: 100
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

  - id: 3
    name: Unseen Val Phase
    description: templates/challenge_phase_3_description.html
    leaderboard_public: False
    is_public: False
    is_submission_public: False
    start_date: 2019-01-01 00:00:00
    end_date: 2099-05-24 23:59:59
    test_annotation_file: annotations/annotations_unseen_val.json
    codename: val_unseen
    max_submissions_per_day: 10
    max_submissions_per_month: 50
    max_submissions: 100
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Seen Test Split
    codename: seen_test
  - id: 2
    name: Unseen Test Split
    codename: unseen_test
  - id: 3
    name: Unseen Val Split
    codename: unseen_val

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 2
    dataset_split_id: 2
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 3
    leaderboard_id: 3
    dataset_split_id: 3
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True